version: 2
updates:
  # Configuration pour les dépendances npm/yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
    reviewers:
      - "Sabrsl"
    assignees:
      - "Sabrsl"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"
    groups:
      react-packages:
        patterns:
          - "react*"
          - "@types/react*"
        exclude-patterns:
          - "react-virtuoso"
      ui-packages:
        patterns:
          - "@radix-ui/*"
      types:
        patterns:
          - "@types/*"
        exclude-patterns:
          - "@types/react*"
    ignore:
      # Ignorer les mises à jour majeures qui pourraient introduire des changements incompatibles
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Exceptions pour les mises à jour de sécurité critiques
      - dependency-name: "axios"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "node-fetch"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]

  # Configuration pour les actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"

  # Configuration pour Docker (si utilisé dans le projet)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "docker"
      include: "scope" 